version: '3.7'
services:
    dwh:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: DfkmrbhbZ
            MYSQL_DATABASE: datawarehouse
            MYSQL_USER: spark
            MYSQL_PASSWORD: Ehj,jhjC
        ports:
            - '3307:3306'
        networks:
          back:
            ipv4_address: 172.18.0.2
          default:
        
    
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
          back:
            ipv4_address: 172.18.0.4
          default:
        logging:
            options:
                max-size: 10m
                max-file: "3"
    

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
            - dwh
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_VERSION=1.10.12
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./sources:/usr/local/airflow/sources
            - ./models:/usr/local/airflow/models
        ports:
            - "8080:8080"
        networks:
          back:
            ipv4_address: 172.18.0.3
          default:        
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

networks:
  back:
    driver: bridge
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.18.0.0/24
       - subnet: 2001:3984:3989::/64 
  default:
    driver: bridge
